- hosts: busybees
  serial: 5
  gather_facts: no
  tasks:
  - name: Set Service
    set_fact:
      app: busybees
  - include: tasks/update-apt-cache.yaml
  - include: tasks/install-connekt-deb.yaml
  - include: tasks/start-service.yaml
