swagger: '2.0'
info:
  title: Connekt API
  description: Fast Forward Communications with the Connekt API
  version: 1.0.0
host: 10.47.0.120
schemes:
  - http
basePath: /v1
produces:
  - application/json
parameters:
  api-key:
    name: x-api-key
    in: header
    description: API key
    required: true
    type: string
    format: string
    default: "connekt-genesis"
  MPlatform:
    name: MPlatform
    in: path
    description: Platform (ios/android/windows/openweb).
    required: true
    type: string
    format: string
  appName:
    name: appName
    in: path
    description: AppName.
    required: true
    type: string
    format: string
  deviceId:
    name: deviceId
    in: path
    description: DeviceId.
    required: true
    type: string
    format: string
paths:
  /registration/push/{MPlatform}/{appName}/{deviceId}:
    put:
      summary: Register New Device
      description: |
        Registrion of a new device. The token from this registration data would be used sending pn..
      parameters:
        - $ref: '#/parameters/api-key'
        - $ref: '#/parameters/MPlatform'
        - $ref: '#/parameters/appName'
        - $ref: '#/parameters/deviceId'
        - name: deviceData
          in: body  
          description: deviceData Defination.
          required: true
          schema:
            $ref: '#/definitions/DeviceDetails'
      tags:
        - Registration
      responses:
        '201':
          description:  Device details created
        '200':
          description: Device details update
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    get:
      summary: Get Device Details
      description: |
       Fetch device details for specific device
      parameters:
        - $ref: '#/parameters/api-key'
        - $ref: '#/parameters/MPlatform'
        - $ref: '#/parameters/appName'
        - $ref: '#/parameters/deviceId' 
      tags:
        - Registration
      responses:
        '200':
          description: Device details 
    delete:
      summary: Delete Device 
      description: |
       Delete specific device
      tags:
        - Registration
      parameters:
        - $ref: '#/parameters/api-key'
        - $ref: '#/parameters/MPlatform'
        - $ref: '#/parameters/appName'
        - $ref: '#/parameters/deviceId' 
      responses:
        '200':
          description: Device deleted succesfully 
  /send/push/{MPlatform}/{appName}:
    post:
      summary: Register New Device
      description: |
        Registrion of a new device. The token from this registration data would be used sending pn..
      parameters:
        - $ref: '#/parameters/api-key'
        - $ref: '#/parameters/MPlatform'
        - $ref: '#/parameters/appName'
        - name: ConnektRequest
          in: body  
          description: ConnektRequest.
          required: true
          schema:
            $ref: '#/definitions/ConnektRequest'
      tags:
        - Send
      responses:
        '201':
          description:  PN Created
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  DeviceDetails:
    type: object
    properties:
      state:
        type: string
        description: An app specific state when this request was triggered.
      model:
        type: string
        description: model of Device
      token:
        type: string
        description: Token.
      brand:
        type: string
        description: brand of Device
      appVersion:
        type: string
        description: appVersion of Device
      osVersion:
        type: string
        description: osVersion of Device.
      userId:
        type: string
        description: UserId 
  ConnektRequest:
    type: object
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      request:
        type: object
      response:
        type: object
        properties:
          message:
            type: string
            description: Error Message

